sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 990724

  alioss:
    access-key-id:
    bucket-name:
    access-key-secret:
    endpoint:

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10